apiVersion: v1
kind: Service
metadata:
    name: kafka-svc-1
    namespace: kafka
spec:
    selector:
        app: kafka-node-1
    ports:
    - name: http
      port: 9092
      nodePort: 30092
    type: NodePort
---
apiVersion: v1
kind: Service
metadata:
    name: kafka-svc-2
    namespace: kafka
spec:
    selector:
        app: kafka-node-2
    ports:
    - name: http
      port: 9092
      nodePort: 30093
    type: NodePort
---
apiVersion: v1
kind: Service
metadata:
    name: kafka-svc-3
    namespace: kafka
spec:
    selector:
        app: kafka-node-3
    ports:
    - name: http
      port: 9092
      nodePort: 30094
    type: NodePort