apiVersion: v1
kind: Service
metadata:
    name: zookeeper-svc-1
    namespace: kafka
spec:
    ports:
    - name: client
      port: 2181
      protocol: TCP
    - name: follower
      port: 2888
      protocol: TCP
    - name: leader
      port: 3888
      protocol: TCP
    selector:
        app: zookeeper-1
    type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
    name: zookeeper-svc-2
    namespace: kafka
spec:
    ports:
    - name: client
      port: 2181
      protocol: TCP
    - name: follower
      port: 2888
      protocol: TCP
    - name: leader
      port: 3888
      protocol: TCP
    selector:
        app: zookeeper-2
    type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
    name: zookeeper-svc-3
    namespace: kafka
spec:
    ports:
    - name: client
      port: 2181
      protocol: TCP
    - name: follower
      port: 2888
      protocol: TCP
    - name: leader
      port: 3888
      protocol: TCP
    selector:
        app: zookeeper-3
    type: ClusterIP